DAOS-2423 log: Use 63-bit indices and terms
daos-stack/raft pull request #38
Opened 2020-11-10 02:37 UTC by liw

Current 31-bit log indices are insufficient for production deployments.
This patch, based on upstream commit 2343e58b by Yossi Gottlieb, changes
both the log index type and the term type to long int.

Signed-off-by: Li Wei <wei.g.li@intel.com>

2020-11-10 08:48 UTC, liw commented
@brianjmurrell, any suggestions on where to look for the build failure?

2020-11-10 20:12 UTC, brianjmurrell requested changes
You need this patch to fix the RPM build: https://github.com/daos-stack/raft/pull/39/commits/9147aa1e6fed18a156cbb308750cc11be0d023cf

You also need to update https://github.com/daos-stack/raft/blob/4f2d60b06af94e59ad10a39142a735914c8d25f8/debian/changelog to fix the Ubuntu build.

2020-11-11 03:27 UTC, kccain approved these changes

2020-11-11 05:44 UTC, liw commented
> You need this patch to fix the RPM build: [9147aa1](https://github.com/daos-stack/raft/commit/9147aa1e6fed18a156cbb308750cc11be0d023cf)
> 
> You also need to update https://github.com/daos-stack/raft/blob/4f2d60b06af94e59ad10a39142a735914c8d25f8/debian/changelog to fix the Ubuntu build.

Done. Thanks.

2020-11-11 06:18 UTC, liw commented
> > You need this patch to fix the RPM build: [9147aa1](https://github.com/daos-stack/raft/commit/9147aa1e6fed18a156cbb308750cc11be0d023cf)
> > You also need to update https://github.com/daos-stack/raft/blob/4f2d60b06af94e59ad10a39142a735914c8d25f8/debian/changelog to fix the Ubuntu build.
> 
> Done. Thanks.

@brianjmurrell, although the build here appears to succeed, the daos PR (https://github.com/daos-stack/daos/pull/3826) still can't find raft-devel 0.7.0. The daos PR is missing anything?

2020-11-11 13:40 UTC, brianjmurrell approved these changes

2020-11-11 14:20 UTC, brianjmurrell commented
> @brianjmurrell, although the build here appears to succeed, the daos PR ([daos-stack/daos#3826](https://github.com/daos-stack/daos/pull/3826)) still can't find raft-devel 0.7.0. The daos PR is missing anything?

I am really glad to see you wanting to test the component (raft) PR before landing the RPM build.  This helps prevent a component update from interfering with everyone else's PRs, as well as master landings, in a case where there is a problem with it.

To this end, I created the `PR-repos:` [commit pragma](https://wiki.hpdd.intel.com/display/CI/Commit+Pragmas) a while ago.  This allows a PR from one project to use the build products of a PR from another repo in it's own build & test.

So in your daos PR commit message, just add a line:

```
PR-repos: raft@PR-38
```

and that daos PR will use the raft RPMs from this PR during it's build & test.

You also need to make a change to https://github.com/daos-stack/daos/blob/0cbbb9aeb90ddc74c6abd31f9713c48a5b18280f/debian/control#L32 to reflect the parallel change you made at https://github.com/daos-stack/daos/blob/0cbbb9aeb90ddc74c6abd31f9713c48a5b18280f/utils/rpms/daos.spec#L58.

2020-11-20 06:38 UTC, merged

2020-11-20 11:22 UTC, ashleypittman commented
This commit looks to have broken DEB builds on master

https://build.hpdd.intel.com/blue/organizations/jenkins/daos-stack%2Fdaos/detail/master/3208/pipeline/90

2020-11-20 13:17 UTC, liw commented
Is it because daos's debian build doesn't specify any raft version? It should be fixed when https://github.com/daos-stack/daos/pull/3826 is merged to daos.