DAOS-5044-test: Fix python bandit errors on log_fuzzer.py
daos-stack/raft pull request #41
Opened 2020-12-17 03:12 UTC by dinghwah

modified: raft/tests/log_fuzzer.py

Signed-off-by: Ding Ho <ding-hwa.ho@intel.com>

2020-12-17 16:23 UTC, jolivier23 requested changes
Can you give a bit more information as to why this is needed in the description?   Why do we need to specify path to gcc, for example? 

==>This error/warning was picked up by python bandit check (similar to pylint with security-check). 
==>Log as the following:
...
Pre-build / Python Bandit check / start_process_with_partial_path – src/rdb/raft/tests/log_fuzzer.py<1s
Pre-build / Python Bandit check / assert_used – src/rdb/raft/tests/log_fuzzer.py<1s
Pre-build / Python Bandit check / assert_used – src/rdb/raft/tests/log_fuzzer.py<1s
Pre-build / Python Bandit check / assert_used – src/rdb/raft/tests/log_fuzzer.py<1s
Pre-build / Python Bandit check / assert_used – src/rdb/raft/tests/log_fuzzer.py<1s
Pre-build / Python Bandit check / assert_used – src/rdb/raft/tests/log_fuzzer.py<1s

2020-12-17 18:25 UTC, jolivier23 approved these changes
Please edit the description to detail the reasons for the patch...not just listing bandit problems but why the changes you made fix them.

Is gcc guaranteed to be installed in /bin ?

==>Thanks for the review and comment, I have updated the description.
        In linux, the full path for gcc should be /bin/gcc or /usr/bin/gcc.

2020-12-18 00:35 UTC, dpquigl approved these changes

2020-12-18 08:49 UTC, liw approved these changes

2020-12-18 08:57 UTC, merged